[build]
  publish = "/public"

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/hello-template"
  function = "transform-hello-template"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "daz1w86h9"


