[build]
  publish = "/public"

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/hello-template"
  function = "transform-hello-template"

[[plugins]]
  package = "netlify-plugin-imagekit"

  [plugins.inputs]
  urlEndpoint = "https://ik.imagekit.io/a1yisxurxo/proxy/"

